### ISSUE TITLE
Error: "newprompt" is not found

### ISSUE THREAD

**Issue by ruv** [Bushmills/yoda#14]
The recent versions cannot start in my environment.

bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

yoda version: 0.6.2, 2022-02-09, commit 901e2d8

The transcript is following:
```
./yoda
./yoda: line 2484: lib["$word"]: bad array subscript
needs:  newprompt
ERROR: not found: newprompt
at 1,18 of /work/forth.data/repo/github/yoda/defaults
```
According to git bisect, the first commit that shows an error is d41927b84 — it reports "ERROR: not found: files" but runs. The first commit that doesn't run REPL is c80d1f48e.

**Comment by Bushmills** [comment]
execute "yoda dependencies" (before launching yoda) once, to rebuild dependencies. Alternatively, simply delete the dependencies file, then yoda will rebuild it when starting.

yoda doesn't yet figure out by itself when libraries have been added, or words moved between them. I intend to add that by setting a version tag in the dependencies file and compare against the version of yoda launched.

dependencies are simply a list of library files, telling yoda which file to consult to resolve specific words. your dependencies don't contain information about where to find newprompt nor files.

this line:
`needs:  newprompt newquery$`
in your defaults asks yoda to include the library files containing these words (upgraded versions of prompt and query, compared to the minimal versions in yoda itself), set through deferred words.

**Comment by ruv** [comment]
Thank you, it works now. 
I expected that it should just work after updating (`git pull`) too.

The `DEPENDENCIES` file was changed and now it doesn't match the git index. Probably it should be ignored (via the `.gitignore` file in git).

**Comment by Bushmills** [comment]
it *is* .gitignored.  the version on your computer has been generated as result of yoda executing.

**Comment by Bushmills** [comment]
well,  dependencies  is.  DEPENDENCIES (in capitals) is a descriptive text file, and not on .gitignore list.
Maybe I should move DEPENDENCIES to the documentation / wiki section on github, rather than adding it as file to yoda download, to reduce potential confusion,

**Comment by ruv** [comment]
> it is .gitignored. the version on your computer has been generated as result of yoda executing.

Oh, I see. 

The `yoda/.git/config` file contains the lines:
```
[core]
  ignorecase = true
```

So it rewrites the `DEPENDENCIES` file (in capitals).

Setting `ignorecase = false` doesn't help, it looks like the underline file system limitations/configurations (WSL v1).

**Comment by Bushmills** [comment]
I've removed DEPENDENCIES, Who wants to read about those, should look into the wiki instead :)

**Comment by ruv** [comment]
For check, I set the file system [case sensitivity](https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity) for the yoda directory. After that it works fine by auto-creating the `dependencies` file when it's absent (regardless of the `DEPENDENCIES` file).
