### ISSUE TITLE
Examples in README.md

### ISSUE THREAD

**Issue by quozl** [Bushmills/yoda#5]
It would be great to see examples of how to use Yoda, such as terminal transcripts, or minimal but functional source files.

**Comment by Bushmills** [comment]
Indeed is yoda regarding examples a bit on the wanting side now. I'd now point towards trivial stuff like dump. Chances are good that there'll be a version of Conway's Life soon.

**Comment by Bushmills** [comment]
New file in tests committed now:  
[Conway's Game of Life](https://github.com/Bushmills/yoda/blob/main/demo/gol)

Instead of linking to example code files in README, I'd rather add it to a link page in the wiki, created for that purpose, and possibly point to that wiki page from README.

**Comment by quozl** [comment]
Thanks!
